export const heroVisualStack = ['React', 'Node', 'MongoDB', 'Tailwind', 'Docker',]

export const techStack = [
  'React',
  'Vite',
  'HTML',
  'CSS',
  'Tailwind CSS',
  'JavaScript',
  'Node.js',
  'Express',
  'MongoDB',
  'MySQL',
  'Mongoose',
  'JWT',
  'Zod',
  'Git',
  'GitHub',
  'Docker',
  'Vercel',
  'Render',
  'Cloudinary',
  'Postman',
  'VS Code',
  'Notion',
]
